# Auto-generated using compose2nix v0.3.2-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."authentik-postgresql" = {
    image = "docker.io/library/postgres:16-alpine";
    volumes = [
      "/containers/authentik/postgresql:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=pg_isready -d \${POSTGRES_DB} -U \${POSTGRES_USER}"
      "--health-interval=30s"
      "--health-retries=5"
      "--health-start-period=20s"
      "--health-timeout=5s"
      "--network-alias=postgresql"
      "--network=arr"
    ];
  };
  systemd.services."podman-authentik-postgresql" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-servarr-root.target"
    ];
    wantedBy = [
      "podman-compose-servarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."authentik-redis" = {
    image = "docker.io/library/redis:alpine";
    volumes = [
      "/containers/authentik/redis:/data:rw"
    ];
    cmd = [ "--save" "60" "1" "--loglevel" "warning" ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=redis-cli ping | grep PONG"
      "--health-interval=30s"
      "--health-retries=5"
      "--health-start-period=20s"
      "--health-timeout=3s"
      "--network-alias=redis"
      "--network=arr"
    ];
  };
  systemd.services."podman-authentik-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-servarr-root.target"
    ];
    wantedBy = [
      "podman-compose-servarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."authentik-server" = {
    image = "ghcr.io/goauthentik/server:2024.10.5";
    environment = {
      "AUTHENTIK_DISABLE_STARTUP_ANALYTICS" = "true";
      "AUTHENTIK_ERROR_REPORTING__ENABLED" = "false";
      "AUTHENTIK_POSTGRESQL__HOST" = "postgresql";
      "AUTHENTIK_REDIS__HOST" = "redis";
    };
    volumes = [
      "/containers/authentik/authentik/custom-templates:/templates:rw"
      "/containers/authentik/authentik/media:/media:rw"
    ];
    ports = [
      "9000:9000/tcp"
      "9443:9443/tcp"
    ];
    cmd = [ "server" ];
    dependsOn = [
      "authentik-postgresql"
      "authentik-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=server"
      "--network=arr"
    ];
  };
  systemd.services."podman-authentik-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-servarr-root.target"
    ];
    wantedBy = [
      "podman-compose-servarr-root.target"
    ];
  };
  virtualisation.oci-containers.containers."authentik-worker" = {
    image = "ghcr.io/goauthentik/server:2024.10.5";
    environment = {
      "AUTHENTIK_DISABLE_STARTUP_ANALYTICS" = "true";
      "AUTHENTIK_ERROR_REPORTING__ENABLED" = "false";
      "AUTHENTIK_POSTGRESQL__HOST" = "postgresql";
      "AUTHENTIK_REDIS__HOST" = "redis";
    };
    volumes = [
      "/containers/authentik/authentik/certs:/certs:rw"
      "/containers/authentik/authentik/custom-templates:/templates:rw"
      "/containers/authentik/authentik/media:/media:rw"
      "/run/podman/podman.sock:/var/run/docker.sock:rw"
    ];
    cmd = [ "worker" ];
    dependsOn = [
      "authentik-postgresql"
      "authentik-redis"
    ];
    user = "root";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=worker"
      "--network=arr"
    ];
  };
  systemd.services."podman-authentik-worker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-servarr-root.target"
    ];
    wantedBy = [
      "podman-compose-servarr-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-servarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
