# https://forums.docker.com/t/docker-using-dnsmasq-as-resolver-forwarder-to-reach-containers-from-host/137390/3
local=/docker/
server=/.docker/127.0.0.11
server=/.projects.docker/127.0.0.11
server=127.0.0.11