{
	"data": "ENC[AES256_GCM,data:XzUby4NFVcJejRGgC7GEI1H2gRAlwvh6ZRXGeITT/z8OyVZFhLelnU5zGXLrDylo0HylWuKTKwC9+XElv9ibXVsAlO8PCPjENRbGZZChRIxou3u/sZUOmCjPDBcODtwsIa2AU7bdYL6EhnhvYS5SUgcBHDr8GIYG/5c85F4Mzom8/fbcXwYgoAO5W8pX6F2eXHCRjDzJSlL0FKOLty16XSj1q6XCdjQcpPjOQIO4F0P5Azl+uEbYpb6Pt3bRWEHDwsm3y2Vcdk4Xb/7BtHp0RsWfEH34d0cMTz0r/YeItkUYoD8uZglHW4EsOqjDheIHhtMd+voKLsdj8J1o83c6y39L3zDLiJqk6tCb7PZWNwDNRSAIn6cp9fahL+h58evnuR3w+ufxzkd95zI2osbj6bzJeI9y79dsTCm0Ij9q9kOr5QTM5xak5wcGVSXQujF4rzpOiReHiwEhAKL3tsbTBWcxn8wznZjK19d6/+7ohDSlQCN9hZcKcKePiN2UtA6GNzLmKWqaohAX4ROJ+r61tUsfTBPMkiv2G59gpUCMN+DpTPxdIabVzoWxgT448Znsvs1exJS1b5kiz24PNTVXllwkwxMq9m7Q4WMH+I39bG4F6NsCUch78LQ2gk37fwR0Nso5qPqvhqYO1hfevRzuz1fhPoWQ79c1kuGQTgro2zgE5tU=,iv:K2WbRM3yItjFPAzf9Ot5XIuOGNJ6tbjVGcKxC6XxkBI=,tag:3vVfcJqlRjjFvU6YfuJHYA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age14cyrlharjqa44tul328cr5gxyj7pxut6zgz8e5el3x3s99f2xujspa0m9e",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZUhaTGI3WUhFRDlzdWZO\nRm9FR1JCb05GR2EvUG16b3dCVHJkN1Q5bUgwClFHd0U0ckc4ZWVpMlVZb2c4dEtv\nemR0eHBlRi9yRi9xakFjcDNMSk1UczAKLS0tIEJKclB3UUFqWmtVK2pHdkQ0eDdr\nL1NlQXV2c3YxWlRDQ2hiZE1scHBEVm8KIMkw2Uz3nEq2PII9efnKIXVYBpfx4pty\nxdAXX7MTnNDLeBt6aD37zOI8t+OvyV4eAn6q6n4J4LdSrdETVXQOtw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age10rfls3ea0mmytzfdffvzxt0yfka742cgzcrs4qygjfp5v5s9pc2s2mpvt6",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOFI1ZGx1YXFoV3pHS1VF\nM3hEaWRWTEsvdFloVGE4d3gvTld3RDB6dEZBCjk0RnRjaGVLTGdWdlZWUTNuaWR3\nUlV0RjI5VUxtaDJHSWdNb0xFNjkycVUKLS0tIDk1K1kvNUovTG5leERNMlpCQlNI\nT296VytwazVJWUxHdU5rcUZNVk92Y3cKjwIvNKcrNFvJ7QSSVt7tMeiHU1HESfbg\n8QfEJ4aqkodm8HRGwGXMv13cAsXUVnKqRORUpNzXFFG9VkxP4BIwzA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-10-13T18:15:24Z",
		"mac": "ENC[AES256_GCM,data:G+bsGsUhBuRQJWs4IPVglAf4i5O0oRfOpek/LdMAr/Xg8mzTWRtAsHSl05tYtkF2ovM1zBQ8i7sxARb5cnOlCV7C0yEaHZnf3PXr4GFpeqlCkQMMoWpe4tP30nN4ylverMxNkHPr55Ku9qh4MRXMsvX/RYSAYI6yTiJM7Df+yiE=,iv:K2FlmTfo3avRjC0gVRwZwNZRwuqGazeXVl2KJpd5ZKY=,tag:tHsbDgy/ivs+mbJzgcUFqA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.9.0"
	}
}