# Do I need this? https://github.com/rasmus-kirk/nixarr?tab=readme-ov-file
# Nice inspiration: https://github.com/painerp/nixos/blob/339554807b155d54b1e9a996d9693fec77d86f39/containers/gluetun.nix

# Alternatively for containers:
# https://github.com/hercules-ci/arion
# https://nixos.wiki/wiki/NixOS_Containers

{ lib, config, inputs, pkgs, ... }:

let
  cfg = config.ncfg.servarr;
  systemUsers = lib.attrNames config.users.users;
in
{
  imports = [
    ./dozzle.nix
    ./recyclarr
    ./gluetun.nix
    ./jellyfin.nix
    ./prowlarr.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./sonarr.nix
    ./tor.nix
  ];

  options.ncfg.servarr = {
    enable = lib.mkEnableOption "the servarr module";
    secretsFolder = lib.mkOption {
      type = lib.types.path;
      default = config.lib.sops.mkSecretsPath "/arr";
      description = "The path to the servarr secrets folder.";
    };
    users = lib.mkOption {
      type = lib.types.listOf (lib.types.enum systemUsers);
      default = [ ];
      description = "The users to add to the servarr and podman groups.";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      inputs.compose2nix.packages.${pkgs.system}.default
      pkgs.docker-compose
    ];

    users.groups.podman.members = cfg.users;
    users.groups.servarr.members = cfg.users;

    # Runtime
    virtualisation.podman = {
      enable = true;
      autoPrune.enable = true;
      dockerCompat = true;
      defaultNetwork.settings = {
        # Required for container networking to be able to use names.
        dns_enabled = true;
      };
    };

    virtualisation.containers.containersConf.settings = {
      # [containers]
      # base_hosts_file="none"
      # https://github.com/containers/common/blob/main/docs%2Fcontainers.conf.5.md#containers-table
      # containers = {
      #   base_hosts_file = ""; # Default
      #   # base_hosts_file = "none";
      #   # base_hosts_file = "image";
      # };
    };

    # Enable container name DNS for non-default Podman networks.
    # https://github.com/NixOS/nixpkgs/issues/226365
    networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

    virtualisation.oci-containers.backend = "podman";

    # Networks
    systemd.services."podman-network-arr" = {
      path = [ pkgs.podman ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "podman network rm -f arr";
      };
      script = ''
        podman network inspect arr || podman network create arr
      '';
      partOf = [ "podman-compose-servarr-root.target" ];
      wantedBy = [ "podman-compose-servarr-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."podman-compose-servarr-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };

}
