# Do I need this? https://github.com/rasmus-kirk/nixarr?tab=readme-ov-file
# Nice inspiration: https://github.com/painerp/nixos/blob/339554807b155d54b1e9a996d9693fec77d86f39/containers/gluetun.nix

# Alternatively for containers:
# https://github.com/hercules-ci/arion
# https://nixos.wiki/wiki/NixOS_Containers

{ lib, config, inputs, pkgs, ... }:

let
  cfg = config.ncfg.servarr;
  # systemUsers = lib.attrNames config.users.users;
in
{
  imports = [
    ./authentik

    ./ddns
    ./dozzle
    ./homarr
    ./nvidia-ctk.nix

    ./dnsmasq
    ./wg-easy.nix

    ./qbit_manage
    ./radarr
    ./sonarr

    ./cloudflared.nix
    ./cross-seed.nix
    ./flaresolverr.nix
    ./recyclarr
    ./gluetun.nix
    ./jellyfin.nix
    ./jellyseerr.nix
    ./prowlarr.nix
    ./qbittorrent.nix
    ./swag-internal.nix
    ./swag.nix
    ./thelounge.nix
    ./tor.nix
  ];

  options.ncfg.servarr = {
    enable = lib.mkEnableOption "the servarr module";
    secretsFolder = lib.mkOption {
      type = lib.types.path;
      default = config.lib.sops.mkSecretsPath "/arr";
      description = "The path to the servarr secrets folder.";
    };
    # users = lib.mkOption {
    #   type = lib.types.listOf (lib.types.enum systemUsers);
    #   default = [ ];
    #   description = "The users to add to the servarr and docker groups.";
    # };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [
      inputs.compose2nix.packages.${pkgs.system}.default
      pkgs.docker-compose
    ];

    # users.groups.docker.members = cfg.users;
    # users.groups.servarr.members = cfg.users;

    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };

    virtualisation.oci-containers.backend = "docker";

    # Networks
    systemd.services."docker-network-0wireguard" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f 0wireguard";
      };
      script = ''
        docker network inspect 0wireguard || docker network create 0wireguard
      '';
      partOf = [ "docker-compose-servarr-root.target" ];
      wantedBy = [ "docker-compose-servarr-root.target" ];
    };
    systemd.services."docker-network-arr" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f arr";
      };
      script = ''
        docker network inspect arr || docker network create arr
      '';
      partOf = [ "docker-compose-servarr-root.target" ];
      wantedBy = [ "docker-compose-servarr-root.target" ];
    };
    systemd.services."docker-network-exposed" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f exposed";
      };
      script = ''
        docker network inspect exposed || docker network create exposed
      '';
      partOf = [ "docker-compose-servarr-root.target" ];
      wantedBy = [ "docker-compose-servarr-root.target" ];
    };
    systemd.services."docker-network-thelounge" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f thelounge";
      };
      script = ''
        docker network inspect thelounge || docker network create thelounge
      '';
      partOf = [ "docker-compose-servarr-root.target" ];
      wantedBy = [ "docker-compose-servarr-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-servarr-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
      wantedBy = [ "multi-user.target" ];
    };
  };

}
