# compose2nix --project servarr -env_files .env
networks:
  arr:
    name: arr
  exposed:
    name: exposed
  thelounge:
    name: thelounge
  authentik:
    name: authentik
    external: true
  ldap:
    name: ldap
    external: true

services:
  dnsmasq:
    image: 4km3/dnsmasq:2.90-r3
    container_name: dnsmasq
    volumes:
      - /CHANGEME/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - 5300:53/tcp
      - 5300:53/udp
      - 54000:51820/udp
      - 54001:51821/tcp
    cap_add:
      - NET_ADMIN
    networks:
      - arr
      - exposed
      - thelounge
      - authentik
      - ldap

  # https://github.com/wg-easy/wg-easy
  # sudo docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw 'password'
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=<Host IP>
      # sudo docker run --rm -it ghcr.io/wg-easy/wg-easy wgpw 'password'
      - PASSWORD_HASH=<Hash>
      - PORT=51821
      - WG_PORT=51820
    # env_file:
    #   - ${config.sops.secrets.wg-easy-env.path}
    volumes:
      - ${PATH_CONFIG_BASE}/wg-easy:/etc/wireguard
    # Handled in dnsmasq
    # ports:
    #   - 54000:51820/udp
    #   - 54001:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    network_mode: service:dnsmasq
    depends_on:
      - dnsmasq

  # https://github.com/qdm12/gluetun
  # https://github.com/qdm12/gluetun-wiki?tab=readme-ov-file#table-of-contents
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8888:8888
    # volumes:
    #   - ./riseup.ovpn:/gluetun/custom.conf:ro
    #   - ./files/vpn-ca.pem:/files/vpn-ca.pem:ro
    #   - ./files/cert.pem:/files/cert.pem:ro
    #   - ./files/key.pem:/files/key.pem:ro
    # env_file:
    #   - ${config.sops.secrets.gluetun-env.path}
    networks:
      - arr

  # https://dozzle.dev/guide/getting-started
  # PODMAN: https://github.com/amir20/dozzle?tab=readme-ov-file#installation-on-podman
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      # - /run/podman/podman.sock:/var/run/docker.sock
    ports:
      # QBit is already using 8080
      - 8090:8080
    networks:
      - arr

  cloudflared-tunnel:
    container_name: cloudflared
    image: cloudflare/cloudflared
    # restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<token>
    # env_file:
    #   - ${config.sops.secrets.cloudflared-env.path}
    networks:
      - exposed

  # https://docs.linuxserver.io/general/swag/#swag
  # https://github.com/linuxserver/reverse-proxy-confs?tab=readme-ov-file#how-to-use-these-reverse-proxy-configs
  # https://www.linuxserver.io/blog/zero-trust-hosting-and-reverse-proxy-via-cloudflare-swag-and-authelia
  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      # - URL=
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - CERTPROVIDER=
      - DNSPLUGIN=cloudflare
      # - EMAIL=
      - ONLY_SUBDOMAINS=false
      - EXTRA_DOMAINS=
      - STAGING=false
      - DOCKER_MODS=linuxserver/mods:swag-cloudflare-real-ip|linuxserver/mods:swag-auto-reload
    # env_file:
    #   - ${config.sops.secrets.swag-env.path}
    volumes:
      - ${PATH_CONFIG_BASE}/swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    # restart: unless-stopped
    networks:
      - exposed

  # https://hotio.dev/containers/jellyfin/
  # Migration: Compare paths in
  # https://jellyfin.org/docs/general/administration/migrate/#migrating-linux-install-to-docker
  # https://hotio.dev/containers/jellyfin/#configuration
  # https://github.com/NixOS/nixpkgs/blob/40916ded4ad5fe4bcc18963217c3a026db505c7f/nixos/modules/services/misc/jellyfin.nix#L27-L63
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - '8096:8096'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/jellyfin:/config
      - ${PATH_MEDIASERVER_DATA_BASE}/media:/data/media
    # https://jellyfin.org/docs/general/installation/container#with-hardware-acceleration
    devices: # Needed for hardware acceleration/transcoding
      - /dev/dri:/dev/dri
      - nvidia.com/gpu=all
    networks:
      - arr
      - ldap
      - exposed

  # https://docs.jellyseerr.dev/
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    ports:
      - 5055:5055
    volumes:
      - ${PATH_CONFIG_BASE}/jellyseerr:/app/config
    # restart: unless-stopped
    networks:
      - arr
      - exposed

  # https://hotio.dev/containers/qbittorrent/#starting-the-container
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent:release-4.6.7
    dns:
      - 1.1.1.1
      - 9.9.9.9
    ports:
      - '8080:8080'
      - '8118:8118'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
      # VPN Config
      # https://hotio.dev/containers/qbittorrent/#wireguard
      - VPN_ENABLED=true
      - VPN_CONF=wg0
      # https://protonvpn.com/vpn-servers
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=192.168.1.0/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN=8080/tcp # Expose WebUI
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - PRIVOXY_ENABLED=true
      - UNBOUND_ENABLED=false
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1 # Disable IPv6
    # devices:
    #   - /dev/net/tun:/dev/net/tun # OPTIONAL, READ THIS(9)
    volumes:
      - ${PATH_CONFIG_BASE}/qbittorrent:/config
      - /CHANGEME:/config/wireguard/wg0.conf
      - ${PATH_MEDIASERVER_DATA_BASE}/torrents:/data/torrents
    networks:
      - arr

  # https://github.com/StuffAnThings/qbit_manage/wiki
  qbit_manage:
    container_name: qbit_manage
    image: ghcr.io/stuffanthings/qbit_manage:latest
    volumes:
      - ${PATH_CONFIG_BASE}/qbit_manage/:/config:rw
      - /CHANGEME:/config/config.yml
      - ${PATH_MEDIASERVER_DATA_BASE}/torrents/:/data/torrents:rw
      - ${PATH_CONFIG_BASE}/qbittorrent:/qbittorrent/:ro
    environment:
      - QBT_RUN=false
      - QBT_SCHEDULE=1440
      - QBT_CONFIG=config.yml
      - QBT_LOGFILE=activity.log
      - QBT_CROSS_SEED=false
      - QBT_RECHECK=false
      - QBT_CAT_UPDATE=false
      - QBT_TAG_UPDATE=false
      - QBT_REM_UNREGISTERED=false
      - QBT_REM_ORPHANED=false
      - QBT_TAG_TRACKER_ERROR=false
      - QBT_TAG_NOHARDLINKS=false
      - QBT_SHARE_LIMITS=false
      - QBT_SKIP_CLEANUP=false
      - QBT_DRY_RUN=false
      - QBT_LOG_LEVEL=INFO
      - QBT_DIVIDER==
      - QBT_WIDTH=100
    # restart: on-failure:2
    networks:
      - arr
    depends_on:
      - qbittorrent

  # https://www.cross-seed.org/docs
  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:6
    container_name: cross-seed
    user: 1000:1000
    ports:
      - '2468:2468'
    volumes:
      - ${PATH_CONFIG_BASE}/cross-seed:/config
      - /CHANGEME:/config/config.js
      - ${PATH_CONFIG_BASE}/qbittorrent/data/BT_backup:/torrents:ro # Keep read-only
      - ${PATH_MEDIASERVER_DATA_BASE}/torrents:/data/torrents
    command: daemon
    # restart: unless-stopped
    networks:
      - arr

  # https://hotio.dev/containers/sonarr/#starting-the-container
  sonarr-tv-hd:
    container_name: sonarr-tv-hd
    image: ghcr.io/hotio/sonarr
    ports:
      - '8989:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/sonarr-tv-hd:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  sonarr-anime:
    container_name: sonarr-anime
    image: ghcr.io/hotio/sonarr
    ports:
      - '8990:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/sonarr-anime:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://hotio.dev/containers/radarr/#starting-the-container
  radarr-movies-hd:
    container_name: radarr-movies-hd
    image: ghcr.io/hotio/radarr
    ports:
      - '7878:7878'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/radarr-movies-hd:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://hotio.dev/containers/radarr/#starting-the-container
  radarr-movies-uhd:
    container_name: radarr-movies-uhd
    image: ghcr.io/hotio/radarr
    ports:
      - '7879:7878'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/radarr-movies-uhd:/config
      - ${PATH_MEDIASERVER_DATA_BASE}:/data
    networks:
      - arr

  # https://hotio.dev/containers/prowlarr/#starting-the-container
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - '9696:9696'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - ${PATH_CONFIG_BASE}/prowlarr:/config
    networks:
      - arr

  flaresolverr:
    container_name: flaresolverr
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    ports:
      - '8191:8191'
    # restart: unless-stopped
    networks:
      - arr

  # https://recyclarr.dev/wiki/installation/docker/
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    # Change this to use config.nix.users.*
    # This is ok as recyclarr is a rootless container
    user: nobody:nogroup
    volumes:
      - ${PATH_CONFIG_BASE}/recyclarr:/config
      - /CHANGEME:/config/recyclarr.yml
      - /CHANGEME2:/config/secrets.yml
    environment:
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      # This is a default
      # - CRON_SCHEDULE=@daily
    networks:
      - arr
    depends_on:
      - sonarr-anime
      - sonarr-tv-hd
      - radarr-movies-hd

  # https://thelounge.chat/docs
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - '9010:9000'
    # restart: always
    user: '1000:1000'
    volumes:
      - ${PATH_CONFIG_BASE}/thelounge:/var/opt/thelounge
    networks:
      - thelounge

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # - /run/podman/podman.sock:/var/run/docker.sock
      - ${PATH_CONFIG_BASE}/homarr/configs:/app${PATH_CONFIG_BASE}s
      - ${PATH_CONFIG_BASE}/homarr/icons:/app/public/icons
      - ${PATH_CONFIG_BASE}/homarr/data:/data
    ports:
      - '7575:7575'
    environment:
      - DISABLE_ANALYTICS=true
    networks:
      - arr
