# compose2nix --project servarr
networks:
  arr:
    name: arr

services:
  # https://github.com/qdm12/gluetun
  # https://github.com/qdm12/gluetun-wiki?tab=readme-ov-file#table-of-contents
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 8888:8888
    # volumes:
    #   - ./riseup.ovpn:/gluetun/custom.conf:ro
    #   - ./files/vpn-ca.pem:/files/vpn-ca.pem:ro
    #   - ./files/cert.pem:/files/cert.pem:ro
    #   - ./files/key.pem:/files/key.pem:ro
    # env_file:
    #   - ${config.sops.secrets.gluetun-env.path}
    networks:
      - arr

  # https://dozzle.dev/guide/getting-started
  # PODMAN: https://github.com/amir20/dozzle?tab=readme-ov-file#installation-on-podman
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /run/user/1000/podman/podman.sock:/var/run/docker.sock
      # Currently using podman with root
      - /run/podman/podman.sock:/var/run/docker.sock
    ports:
      # QBit is already using 8080
      - 8090:8080
    networks:
      - arr

  # https://hotio.dev/containers/qbittorrent/#starting-the-container
  qbittorrent:
    container_name: qbittorrent
    image: ghcr.io/hotio/qbittorrent
    ports:
      - '8080:8080'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      - WEBUI_PORTS=8080/tcp,8080/udp
    volumes:
      - /data/config/qBit:/config
      - /data/torrents:/data/torrents
    networks:
      - arr

  # https://hotio.dev/containers/sonarr/#starting-the-container
  # sonarr:
  #   container_name: sonarr
  #   image: ghcr.io/hotio/sonarr
  #   ports:
  #     - '8989:8989'
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - UMASK=002
  #     # Set as config.time.timeZone
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /data/config/sonarr:/config
  #     - /data:/data
  #   networks:
  #     - arr

  sonarr-anime:
    container_name: sonarr-anime
    image: ghcr.io/hotio/sonarr
    ports:
      - '8990:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - /data/config/sonarr-anime:/config
      - /data:/data
    networks:
      - arr

  # https://hotio.dev/containers/radarr/#starting-the-container
  radarr-movies-hd:
    container_name: radarr-movies-hd
    image: ghcr.io/hotio/radarr
    ports:
      - '7878:7878'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
    volumes:
      - /data/config/radarr-movies-hd:/config
      - /data:/data
    networks:
      - arr

  # https://hotio.dev/containers/prowlarr/#starting-the-container
  prowlarr:
    container_name: prowlarr
    image: ghcr.io/hotio/prowlarr
    ports:
      - '9696:9696'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    volumes:
      - /data/config/prowlarr:/config
    networks:
      - arr

  flaresolverr:
    container_name: flaresolverr
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      # Set as config.time.timeZone
      - TZ=Etc/UTC
    ports:
      - '8191:8191'
    restart: unless-stopped
    networks:
      - arr

  # https://recyclarr.dev/wiki/installation/docker/
  recyclarr:
    container_name: recyclarr
    image: ghcr.io/recyclarr/recyclarr
    # Change this to use config.nix.users.*
    # This is ok as recyclarr is a rootless container
    user: nobody:nogroup
    volumes:
      - /data/config/recyclarr:/config
      - /CHANGEME:/config/recyclarr.yml
      - /CHANGEME2:/config/secrets.yml
    environment:
      # Set as config.time.timeZone
      - TZ=Etc/UTC
      # This is a default
      # - CRON_SCHEDULE=@daily
    networks:
      - arr
    depends_on:
      - sonarr-anime
      - radarr-movies-hd
